//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 01:46:29 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vbank.hfu.de/")
package de.hfu.vbank;
